<a href="https://colab.research.google.com/github/mady1258/Intro-to-python/blob/main/codingchallenge10%2611.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Coding challenge part 10 for section 8

#Calculate the value of mathematical expression x*(x+5)^2 where x= 5 using lambda expression.

math = (lambda x: x*(x+5)**2)(5)
print(math)

500


In [11]:
#Coding challenge 11

#Coding challenge part 11


#Consider a list in Python which includes prices of all the items in a store.

#Build a function to discount the price of all the products by 10%.

#Use map to apply the function to all the elements of the list so that all the product prices are discounted.

itemsPrices = [100, 120, 55, 2001, 35, 25, 19]
def disc(price):
  price = price*.95
  return price

discountedprices = list(map(disc,itemsPrices))
print (discountedprices)

[95.0, 114.0, 52.25, 1900.9499999999998, 33.25, 23.75, 18.05]


In [6]:
import numpy as np

a = np.array([1,2])
b = np.array([3,4])
dot = 0

for e, f in zip(a, b):
  dot += e*f
dot


11

In [9]:
# Matricies
A = np.array([[1,2],[3,4,]])
B = np.array([[1,2,3],[4,5,6]])

In [10]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [11]:
A@B

array([[ 9, 12, 15],
       [19, 26, 33]])

In [16]:
a = np.arange(0,18,2).reshape(3,3)
a

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [1]:


x = np.arange(-6,6,1)
x[x<0]=0
x

...

NameError: ignored